# -*- coding: utf-8 -*-
"""SameProductServer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llEjDwTiBnY1ja2aZE7o346Az0oJXxU_
"""

# Cài đặt các thư viện cần thiết
!pip install pandas numpy scikit-learn
!pip install tensorflow-recommenders --no-deps
!pip install tensorflow==2.15.0
!pip install flask flask-cors pyngrok

# Import các thư viện cần thiết
import tensorflow as tf
import tensorflow_recommenders as tfrs
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity
from tensorflow.keras.layers import StringLookup, Embedding
from flask import Flask, jsonify, request
from flask_cors import CORS
from pyngrok import ngrok

from google.colab import drive
drive.mount('/content/drive')

# Đọc dữ liệu sản phẩm và đánh giá
product_data = pd.read_csv('/content/drive/MyDrive/Data/products.csv')
reviews_data = pd.read_csv('/content/drive/MyDrive/Data/reviews.csv')